export const navigation = {
    statistieken: 'statistieken',
    intro: 'intro',
    home: 'home',
    voorspellen: 'voorspellen',
    dashboard: 'dashboard',
    poules: 'poules',
    test: 'test',
    punten: 'punten',
    poule: 'poule',
    overview: 'overview',
    addpoule: 'addpoule',
    acceptinvite: 'acceptinvite',
    adddeelnemer: 'adddeelnemer',
};
